name: coverage

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

env:
  nim-version: stable

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: |
          nimble install coco nimPNG -y
          coco --target "tests/**/*.nim" --cov 'src/**/*.nim' --cov '!tests' --compiler="--opt:speed -d:debug --verbosity:0 --hints:off --lineDir:on"
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
