name: coverage

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

env:
  nim-version: stable

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}

      - name: "Install system packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov build-essential

      - name: "Install Nim packages"
        run: nimble install coco nimPNG -y

      - name: "Generate Coverage"
        run: coco --target "tests/**/*.nim" --cov 'src/**/*.nim' --cov '!tests' --cov '!nimcache' --compiler="--opt:speed -d:debug --verbosity:0 --hints:off --lineDir:on"

      - uses: codecov/codecov-action@v2
        with:
          files: ./lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
