name: nim

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: ["stable", "devel"]
    name: Nim ${{ matrix.nim }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble test -y
